import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static final ValueNotifier<String> currentLanguage = ValueNotifier("English");

  static const Map<String, Map<String, String>> _translations = {
    "English": {
      "dashboard": "Dashboard",
      "pos": "Open POS",
      "kitchen": "Kitchen",
      "analytics": "Analytics",
      "settings": "Settings",
      "inventory": "Inventory",
      "revenue": "Revenue",
      "orders": "Orders",
      "active_tables": "Active Tables",
      "available_tables": "Available Tables",
      "total_revenue": "Total Revenue",
      "today_sales": "Today's Sales",
      "popular_items": "Popular Items",
      "bulk_import": "Bulk Import",
      "master_reset": "Master Reset",
      "categories": "Categories",
      "system_mgmt": "System Management",
      "save_item": "Save Item",
      "item_name": "Item Name",
      "price": "Price",
      "dine_in": "DINE IN",
      "takeaway": "TAKEAWAY",
      "bill": "BILL",
      "kot": "KOT",
      "both": "BOTH",
      "clear_table": "CLEAR TABLE",
      "cancel_order": "Cancel Order",
      "search": "Search Item...",
      "qty": "Qty",
      "add": "Add +",
      "rate": "Rate",
      "amount": "Amount",
      "total": "Total",
      "grand_total": "Grand Total",
      "tax": "Tax (GST 5%)",
      "cart_empty": "Cart is empty!",
      "printing": "PRINTING...",
      "all_categories": "All Categories",
      "serial": "#",
      "daily": "Daily",
      "weekly": "Weekly",
      "monthly": "Monthly",
      "all": "All",
      "overview": "DASHBOARD OVERVIEW",
      "item_sales": "ITEM-WISE SALES",
      "cat_sales": "CATEGORY-WISE SALES",
      "export_csv": "EXPORT CSV",
      "start_order": "Start New Order",
      "detailed_reports": "Detailed Reports",
      "stock_availability": "Stock & Availability",
      "today_rev": "Today's Revenue",
      "today_exp": "Today's Expenses",
      "net_profit": "Net Profit",
      "adv_analytics": "Advanced Analytics",
      "discount": "Discount",
    },
    "Telugu": {
      "dashboard": "డ్యాష్‌బోర్డ్",
      "pos": "పిఓఎస్ తెరవండి",
      "kitchen": "వంటగది",
      "analytics": "విశ్లేషణలు",
      "settings": "సెట్టింగులు",
      "inventory": "శెట్టింగులు",
      "revenue": "రాబడి",
      "orders": "ఆర్డర్లు",
      "active_tables": "క్రియాశీల టేబుల్స్",
      "available_tables": "ఖాళీ టేబుల్స్",
      "total_revenue": "మొత్తం రాబడి",
      "today_sales": "ఈరోజు అమ్మకాలు",
      "popular_items": "ప్రసిద్ధ వస్తువులు",
      "bulk_import": "బల్క్ ఇంపోర్ట్",
      "master_reset": "మాస్టర్ రీసెట్",
      "categories": "వర్గాలు",
      "system_mgmt": "సిస్టమ్ మేనేజ్మెంట్",
      "save_item": "వస్తువును సేవ్ చేయి",
      "item_name": "వస్తువు పేరు",
      "price": "ధర",
      "dine_in": "డైన్ ఇన్",
      "takeaway": "టేక్ అవే",
      "bill": "బిల్లు",
      "kot": "కేఓటీ (KOT)",
      "both": "రెండూ",
      "clear_table": "టేబుల్ ఖాళీ చేయి",
      "cancel_order": "ఆర్డర్ రద్దు చేయి",
      "search": "వస్తువును వెతకండి...",
      "qty": "పరిమాణం",
      "add": "కలపండి +",
      "rate": "ధర",
      "amount": "మొత్తం",
      "total": "మొత్తం :",
      "grand_total": "మొత్తం చెల్లింపు",
      "tax": "పన్ను (GST 5%)",
      "cart_empty": "కార్ట్ ఖాళీగా ఉంది!",
      "printing": "ముద్రిస్తోంది...",
      "all_categories": "అన్ని వర్గాలు",
      "serial": "సంఖ్య",
      "daily": "రోజువారీ",
      "weekly": "వారానికోసారి",
      "monthly": "నెలవారీ",
      "all": "అన్నీ",
      "overview": "డ్యాష్‌బోర్డ్ అవలోకనం",
      "item_sales": "వస్తువుల ప్రకారం అమ్మకాలు",
      "cat_sales": "వర్గం ప్రకారం అమ్మకాలు",
      "export_csv": "CSV ని ఎగుమతి చేయండి",
      "start_order": "కొత్త ఆర్డర్ ప్రారంభించండి",
      "detailed_reports": "వివరణాత్మక నివేదికలు",
      "stock_availability": "స్టాక్ మరియు లభ్యత",
      "today_rev": "ఈరోజు రాబడి",
      "today_exp": "ఈరోజు ఖర్చులు",
      "net_profit": "నికర లాభం",
      "adv_analytics": "అధునాతన విశ్లేషణలు",
      "discount": "డిస్కౌంట్",
    },
    "Hindi": {
      "dashboard": "डैशबोर्ड",
      "pos": "पीओएस खोलें",
      "kitchen": "रसोई",
      "analytics": "विश्लेषण",
      "settings": "सेटिंग्स",
      "inventory": "माल",
      "revenue": "राजस्व",
      "orders": "आदेश",
      "active_tables": "सक्रिय टेबल",
      "available_tables": "उपलब्ध टेबल",
      "total_revenue": "कुल राजस्व",
      "today_sales": "आज की बिक्री",
      "popular_items": "लोकप्रिय वस्तुएं",
      "bulk_import": "बल्कि आयात",
      "master_reset": "मास्टर रीसेट",
      "categories": "श्रेणियाँ",
      "system_mgmt": "सिस्टम प्रबंधन",
      "save_item": "आइटम सहेजें",
      "item_name": "आइटम का नाम",
      "price": "कीमत",
      "dine_in": "डाइन इन",
      "takeaway": "टेकअवे",
      "bill": "बिल",
      "kot": "केओटी (KOT)",
      "both": "दोनों",
      "clear_table": "टेबल साफ करें",
      "cancel_order": "ऑर्डर रद्द करें",
      "search": "आइटम खोजें...",
      "qty": "मात्रा",
      "add": "जोड़ें +",
      "rate": "दर",
      "amount": "रकम",
      "total": "कुल :",
      "grand_total": "कुल योग",
      "tax": "कर (GST 5%)",
      "cart_empty": "कार्ट खाली है!",
      "printing": "मुद्रण...",
      "all_categories": "सभी श्रेणियाँ",
      "serial": "क्र.सं.",
      "daily": "दैनिक",
      "weekly": "साप्ताहिक",
      "monthly": "मासिक",
      "all": "सभी",
      "overview": "डैशबोर्ड अवलोकन",
      "item_sales": "आइटम-वार बिक्री",
      "cat_sales": "श्रेणी-वार बिक्री",
      "export_csv": "CSV निर्यात करें",
      "start_order": "नया ऑर्डर शुरू करें",
      "detailed_reports": "विस्तृत रिपोर्ट",
      "stock_availability": "स्टॉक और उपलब्धता",
      "today_rev": "आज का राजस्व",
      "today_exp": "आज के खर्च",
      "net_profit": "शुद्ध लाभ",
      "adv_analytics": "उन्नत विश्लेषण",
      "discount": "छूट",
    }
  };

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    currentLanguage.value = prefs.getString("selected_language") ?? "English";
  }

  static Future<void> changeLanguage(String lang) async {
    currentLanguage.value = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString("selected_language", lang);
  }

  static String translate(String key) {
    return _translations[currentLanguage.value]?[key] ?? key;
  }
}
